apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: springboot-template
  title: Spring Boot Service
  description: Standard Spring Boot (Java) microservice with recommended configuration for HMCTS
  tags:
    - recommended
    - java
spec:
  owner: Platform Engineering (#rpe)
  templater: cookiecutter
  type: service
  schema:
    required:
      - product
      - component_id
      - description
    properties:
      product:
        title: Product
        type: string
        description: Product this component belongs to, normally the team name, e.g. cmc
      component_id:
        title: Component name
        type: string
        description: Name of the component, e.g. backend
      description:
        title: Description
        type: string
        description: Description of the component
      http_port:
        title: Port
        type: integer
        default: 8080
        description: The port to run the app on
